// auth actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// job board actions
export const EDIT_JOB = 'EDIT_JOB';
export const CLOSE_EDIT_JOB_MODAL = 'CLOSE_EDIT_JOB_MODAL';
export const JOB_UPDATED = 'JOB_UPDATED';
export const SET_EDITING_JOB_NAME = 'SET_EDITING_JOB_NAME';
export const SET_EDITING_JOB_PROJECT_IDS = 'SET_EDITING_JOB_PROJECT_IDS';
export const SET_EDITING_JOB_RESOURCE_IDS = 'SET_EDITING_JOB_RESOURCE_IDS';